### PR TITLE
🤖📯 GitHub OpenAPI Update

### PR DESCRIPTION
**Pull request by octokitbot**
I found new changes in [GitHub's official OpenAPI specifications](https://github.com/github/rest-api-description) and thought I'd let you know about it 👋🤖

I can't tell if the changes include fixes, features, breaking changes or just cache updates, you'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/openapi/blob/main/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

### CODE REVIEW

**Review by gr2m — COMMENTED** [review]
... ehmmm
image

**Comment by nickfloyd** [comment]
> ... ehmmm image

How might you approach a change of this size (obviously locally)?  This either is not right, or we've got a lot of changes to the OpenAPI schema / generated schema to review.  What are some of the best ways to detect generation smells here - or is this something that is possible and needs review? 

Just seeking some wisdom before I try to dig in.

**Comment by gr2m** [comment]
This changset cannot be right, I've never seen something like this before. I'd check it out locally first and understand where this huge diff is coming from. I always look for the diffs in [`generated/api.github.com.json`](https://github.com/octokit/openapi/blob/main/generated/api.github.com.json) first, it's the most important file

**Comment by nickfloyd** [comment]
Based on some digging I did it looks like a couple of merges into rest_api_descriptions that was later reverted caused this. I feel like we should close this and regnerate.

**Comment by nickfloyd** [comment]
Closing in favor of getting a regenerated version from what's actually in main / rest_api_descriptions

**Pull request closed without merging**
