### PR TITLE
feat: add support for GHES 3.9, add new endpoints

### PR DESCRIPTION
**Pull request by wolfy1339**
Resolves #ISSUE_NUMBER

---

### Before the change?

- OpenAPI updates were not working due to GHES 3.9
- Commit diffs were too big to view on GitHub

### After the change?

- OpenAPI updates will not fail anymore

### Other information

- ***

### Pull request checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:

- N/A

### Pull request type

Please add the corresponding label for change this PR introduces:

- Feature/model/API additions: `Type: Feature`

---

### CODE REVIEW

**Comment by kfcampbell** [comment]
I'm unable to view the diff on GitHub here either, sadly. Pulling it down locally means I can view the diff, though it's too big to mentally parse effectively. Is it all GHES 3.9 support and generated changes (and if so, from where)?

**Comment by kfcampbell** [comment]
Also, I'm not sure if GHES 3.9 has a release date yet. Perhaps this PR would be better held until then.

**Comment by wolfy1339** [comment]
You can view the changes individually on GitHub.

The GHES 3.9 support is complete. It's all the schema downloaded from GitHub and generated with the patches in this repo

**Comment by wolfy1339** [comment]
https://github.com/github/rest-api-description/tree/main/descriptions/ghes-3.9

The specs have been released, and a release date in the docs, so I would think it's been released officially here:
https://github.com/github/docs/tree/main/src/ghes-releases/lib/enterprise-dates.json

**Comment by kfcampbell** [comment]
@wolfy1339 makes sense! I've seen some posts internally about 3.9 release candidates still being worked on; I didn't know the schema had already been released. Thanks!

**Review by kfcampbell — APPROVED** [review]

**Pull request merged**
