### PR TITLE
feat: remove ruleset objects, various description updates

### PR DESCRIPTION
**Pull request by octokitbot**
I found new changes in [GitHub's official OpenAPI specifications](https://github.com/github/rest-api-description) and thought I'd let you know about it 👋🤖

I can't tell if the changes include fixes, features, breaking changes or just cache updates, you'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/openapi/blob/main/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

### CODE REVIEW

**Review by bitcoinfinancier — APPROVED** [review]

**Review by bitcoinfinancier — APPROVED** [review]

**Comment by kfcampbell** [comment]
Interestingly, the tests are failing due to an invalid JSON description. Here's the offending material in `generated/api.github.com.deref.json`

<details><summary>JSON snippet</summary>
<p>

```json
   "/orgs/{org}/blocks/{username}": {
      "get": {
        "summary": "Check if a user is blocked by an organization",
        "description": "Returns a 204 if the given user is blocked by the given organization. Returns a 404 if the organization is not blocking the user, or if the user account has been identified as spam by GitHub.",
        "tags": [
          "orgs"
        ],
        "operationId": "orgs/check-blocked-user",
        "externalDocs": {
          "description": "API method documentation",
          "url": "https://docs.github.com/rest/reference/orgs#check-if-a-user-is-blocked-by-an-organization"
        },
        "parameters": [
          {
            "name": "org",
            "description": "The organization name. The name is not case sensitive.",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          "304": {
            "description": "Not modified"
          },
          "401": {
            "description": "Requires authentication",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Basic Error",
                  "description": "Basic Error",
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "documentation_url": {
                      "type": "string"
                    },
                    "url": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "x-github": {
          "githubCloudOnly": false,
          "enabledForGitHubApps": true,
          "category": "orgs",
          "subcategory": "blocking"
        },
        "x-octokit": {}
      },
      "put": {
        "summary": "Block a user from an organization",
        "description": "Blocks the given user on behalf of the specified organization and returns a 204. If the organization cannot block the given user a 422 is returned.",
        "tags": [
          "orgs"
        ],
        "operationId": "orgs/block-user",
        "externalDocs": {
          "description": "API method documentation",
          "url": "https://docs.github.com/rest/reference/orgs#block-a-user-from-an-organization"
        },
        "parameters": [
          {
            "name": "org",
            "description": "The organization name. The name is not case sensitive.",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Basic Error",
                  "description": "Basic Error",
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "documentation_url": {
                      "type": "string"
                    },
                    "url": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Error",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Basic Error",
                  "description": "Basic Error",
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "documentation_url": {
                      "type": "string"
                    },
                    "url": {
                      "type": "string"
                    },
                    "status": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },
```


</p>
</details> 


Here's the other offense, from `generated/ghec.deref.json`: 

<details><summary>JSON snippet</summary>
<p>

```json
"/orgs/{org}/packages": {
      "get": {
        "summary": "List packages for an organization",
        "description": "Lists packages in an organization readable by the user.\n\nTo use this endpoint, you must authenticate using an access token with the `read:packages` scope. If the `package_type` belongs to a registry that only supports repository-scoped permissions, your token must also include the `repo` scope. For the list of GitHub Packages registries that only support repository-scoped permissions, see \"[About permissions for GitHub Packages](https://docs.github.com/enterprise-cloud@latest//packages/learn-github-packages/about-permissions-for-github-packages#permissions-for-repository-scoped-packages).\"",
        "tags": [
          "packages"
        ],
        "operationId": "packages/list-packages-for-organization",
        "externalDocs": {
          "description": "API method documentation",
          "url": "https://docs.github.com/enterprise-cloud@latest//rest/reference/packages#list-packages-for-an-organization"
        },
        "parameters": [
          {
            "name": "package_type",
            "description": "The type of supported package. Packages in GitHub's Gradle registry have the type `maven`. Docker images pushed to GitHub's Container registry (`ghcr.io`) have the type `container`. You can use the type `docker` to find images that were pushed to GitHub's Docker registry (`docker.pkg.github.com`), even if these have now been migrated to the Container registry.",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "enum": [
                "npm",
                "maven",
                "rubygems",
                "docker",
                "nuget",
                "container"
              ]
            }
          },
          {
            "name": "org",
            "description": "The organization name. The name is not case sensitive.",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "visibility",
            "description": "The selected visibility of the packages.  This parameter is optional and only filters an existing result set.\n\nThe `internal` visibility is only supported for GitHub Packages registries that allow for granular permissions. For other ecosystems `internal` is synonymous with `private`.\nFor the list of GitHub Packages registries that support granular permissions, see \"[About permissions for GitHub Packages](https://docs.github.com/enterprise-cloud@latest//packages/learn-github-packages/about-permissions-for-github-packages#granular-permissions-for-userorganization-scoped-packages).\"",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string",
              "enum": [
                "public",
                "private",
                "internal"
              ]
            }
          },
          {
            "name": "page",
            "description": "Page number of the results to fetch.",
            "in": "query",
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "name": "per_page",
            "description": "The number of results per page (max 100).",
            "in": "query",
            "schema": {
              "type": "integer",
              "default": 30
            }
          }
        },
        "responses": {
```
</p>
</details> 

These are both org endpoints, though they are different ones so it seems unlikely the error is due to a root schema issue. More investigation here is required.

**Comment by kfcampbell** [comment]
@gr2m I'd like to ask you for advice about how I might troubleshoot this further if that's okay!

**Comment by gr2m** [comment]
The problem seems to be that the path `paths."/orgs/{org}/packages/{package_type}/{package_name}/restore"` exists twice and that is forbidden is forbidden in JSON Schema

**Comment by gr2m** [comment]
It's not the case at https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json, so I'm not sure what's happening

**Comment by gr2m** [comment]
Also this is invalid JSON:

```
        "parameters": [
          {
            "$ref": "#/components/parameters/package-type"
          },
          {
            "$ref": "#/components/parameters/package-name"
          },
          "422": {
            "$ref": "#/components/responses/validation_failed"
          },
          "500": {
            "$ref": "#/components/responses/internal_error"
          }
        },
```

An array item can be `"422": { ... }` without being wrapped in braces `{ "422": { ... } }`

**Comment by gr2m** [comment]
Running `npm run download` resolves that problem, but also seems to introduce lots of new changes that will need to be reviewed :(

**Comment by ollie-iterators** [comment]
Perhaps https://github.com/octokit/openapi/pull/364 should be merged before this PR is merged.

**Comment by nickfloyd** [comment]
There appear to be more issues with [ghes-3.8-diff-to-ghes-3.9.json](https://github.com/octokit/openapi/blob/5a3aa0a59b88cfd1ed98263bb56fe9bdc1bbf26a/generated/ghes-3.8-diff-to-ghes-3.9.json).

*  [/users/{username}/subscriptions](https://github.com/octokit/openapi/blob/5a3aa0a59b88cfd1ed98263bb56fe9bdc1bbf26a/generated/ghes-3.8-diff-to-ghes-3.9.json#L3651) : duplicate value
*  [/users/{username}/installation](https://github.com/octokit/openapi/blob/5a3aa0a59b88cfd1ed98263bb56fe9bdc1bbf26a/generated/ghes-3.8-diff-to-ghes-3.9.json#L5492) : The character U+2019 "’" could be confused with the ASCII character U+0060 "`", which is more common in source code.
* [sponsorship-created/parameters](https://github.com/octokit/openapi/blob/5a3aa0a59b88cfd1ed98263bb56fe9bdc1bbf26a/generated/ghes-3.8-diff-to-ghes-3.9.json#L25935) : appears to be missing a closing bracket for the collection
* [team-edited](https://github.com/octokit/openapi/blob/5a3aa0a59b88cfd1ed98263bb56fe9bdc1bbf26a/generated/ghes-3.8-diff-to-ghes-3.9.json#L27266) : is a duplicate object
* [workflow-run-requested](https://github.com/octokit/openapi/blob/5a3aa0a59b88cfd1ed98263bb56fe9bdc1bbf26a/generated/ghes-3.8-diff-to-ghes-3.9.json#L28683) : End of file expected. Most likely from the missing bracket from above

**Pull request closed without merging**
