### PR TITLE
feat: removes support for GHES 3.5 and adds new properties on codespace endpoints, description updates, and many property type updates

### PR DESCRIPTION
**Pull request by octokitbot**
I found new changes in [GitHub's official OpenAPI specifications](https://github.com/github/rest-api-description) and thought I'd let you know about it 👋🤖

I can't tell if the changes include fixes, features, breaking changes or just cache updates, you'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/openapi/blob/main/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

### CODE REVIEW

**Comment by kfcampbell** [comment]
This diff is too big to display on GitHub. When viewing locally, I'm able to see the diff but it's far too large to make sense of with a single commit message. I'm unsure of what the best action to take is here between not merging or merging as-is.

**Comment by gr2m** [comment]
> it's far too large to make sense of with a single commit message

I would merge with some useful commit message that roughly describes the most important changes, and make sure to use `feat:` or `fix:` depending on what changes are in there.

Then after the release has been created on GitHub, I'd manually update the release notes to include all the changes in detail

**Comment by wolfy1339** [comment]
Your best bet is to filter changes to only include the `generated/` folder, and ignore the `diff` files

Here's a summary of the changes I spotted

- New `geo` property on codespace endpoints
- Remove `key` property on codespace endpoint
- Description updates
- Property type updates

**Comment by gr2m** [comment]
> Your best bet is to filter changes to only include the `generated/` folder, and ignore the `diff` files

that's a good pointer. We could add this instruction to the pull request body of this automated PR, so future maintainers (and our future selfs) won't wonder how to review the PR if the diff is too big

**Review by nickfloyd — APPROVED** [review]

**Comment by nickfloyd** [comment]
RE: looking at the changes

I finally landed on using GitHub Desktop - it displays changesets nicely and is pretty snappy. I also like going directly to the descriptions and diffing from the generated folder as @wolfy1339 suggests.

Screenshot 2023-05-25 at 11 55 50 AM

**Review by nickfloyd — APPROVED** [review]

**Comment by wolfy1339** [comment]
Looks like GHES 3.9 was pushed back to June 1st according to a commit made in the `github/docs` repo: https://github.com/github/docs/commit/cd9b545ef1a07dd5984cb8f2aec44d724a9bcc0d

How do we want to handle that, since we have already published the schemas and types, and any subsequent update between now and the new release date will delete them

**Comment by kfcampbell** [comment]
Perhaps the easiest thing to do from a maintenance standpoint is to wait the (now 2) days until June 1st and block releases in the meantime. Retracting the types until then may be more responsible but it would mean more churn and effort required.

**Comment by oscard0m** [comment]
3.5 GHES has been deprecated officially. I added an extra commit with this BREAKING change.

I also added a commit description to each commit so there is more info about each introduced change.

**Review by wolfy1339 — APPROVED** [review]

**Pull request merged**
