### PR TITLE
feat: GHES 3.10

### LINKED ISSUE #389: [MAINT]: Fix build command to support GHES 3.10
### Describe the need

The current build process is broken due to GHES version 3.10 release.  The current override script only supports one digit in each of the version parts which is causing the build process to fail.

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Jman420**
Resolves #389 

---

### Before the change?
- build process fails due to incorrect parsing of GHES v3.10 from API JSON files.  Parsing only supports one digit in each version part.

### After the change?
- build process succeedes.  Parsing includes multiple digits in each version part.

### Pull request checklist

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes
- [x] No

---

### CODE REVIEW

**Comment by Jman420** [comment]
I did not update all the cache or generated files.  For some reason which I haven't dug into the build process fails when I try to download fresh copies of the cache and run build against them.  Interested to see if the same issue is seen on GitHubActions.

**Review by gr2m — APPROVED** [review]
Thanks!

**Comment by Jman420** [comment]
Just to note; the error in the failing Dry-run update process is the same error that I get when I build locally.  I am not sure what the source of that issue is.

**Comment by gr2m** [comment]
yeah it's unrelated to this pull request

**Pull request merged**
