### PR TITLE
feat: many unreleased OpenAPI updates

### PR DESCRIPTION
**Pull request by octokitbot**
I found new changes in [GitHub's official OpenAPI specifications](https://github.com/github/rest-api-description) and thought I'd let you know about it 👋🤖

I can't tell if the changes include fixes, features, breaking changes or just cache updates, you'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/openapi/blob/main/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

### CODE REVIEW

**Comment by wolfy1339** [comment]
Splitting this up in multiple commits, so hopefully it can be reviewed more easily

**Comment by wolfy1339** [comment]
The diff is so big that GitHub's UI won't allow for a review to be submitted.

This will need manual merging from an administrator

**Review by wolfy1339 — APPROVED** [review]

**Comment by wolfy1339** [comment]
🤔 That's odd

The tests are failing because of invalid JSON

**Comment by ollie-iterators** [comment]
What is the plan for getting this merged? Should it get split up into different parts?

**Comment by wolfy1339** [comment]
It will be up to other maintainers as to how to handle this.

Currently the JSON isn't able to be parsed, there's a syntax error in it somewhere, that's the biggest hold up atm

Ping @kfcampbell @nickfloyd @gr2m

**Review by wolfy1339 — APPROVED** [review]

**Comment by kfcampbell** [comment]
@wolfy1339 do you mind explaining to me how the build got fixed here? Was it due to schema updates that came through and fixed the JSON?

**Comment by wolfy1339** [comment]
I just ran the update process locally, and it seemed to have just fixed itself with the schema updates that came through

**Pull request merged**
