### PR TITLE
feat: new deployment protection rule endpoints, new private reporting of security vulnerability endpoint,

### PR DESCRIPTION
**Pull request by octokitbot**
I found new changes in [GitHub's official OpenAPI specifications](https://github.com/github/rest-api-description) and thought I'd let you know about it 👋🤖

I can't tell if the changes include fixes, features, breaking changes or just cache updates, you'll have to figure that out on yourself and adapt the commit messages accordingly to trigger the right release, see [our commit message conventions](https://github.com/octokit/openapi/blob/main/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).

### CODE REVIEW

**Review by wolfy1339 — APPROVED** [review]

**Comment by wolfy1339** [comment]
Something is going on with GitHub, it won't trigger the `update_dry_run` worflow

**Comment by wolfy1339** [comment]
It seems that the workflow did run this time.

Fixing the linting issue should allow this to be merged

**Comment by nickfloyd** [comment]
> Fixing the linting issue should allow this to be merged

I'm on it.  Thx for the continued help here ❤️

**Comment by nickfloyd** [comment]
I should've seen that coming... the dry run is frozen again 🤦‍♂️ - not sure what's causing that...

**Pull request merged**
